package de.christian2003.petrolindex.application.analysis.dto


/**
 * DTO stores the data lines that were generated by the data line generator.
 *
 * @param volumes                   Data points for the volume data line.
 * @param totalPrices               Data points for the total price data line.
 * @param distancesTraveled         Data points for the distance traveled data line.
 * @param pricePerLiter             Data points for the price per liter data line.
 * @param volumesCount              Total count of values from which the volume data line was generated.
 * @param totalPricesCount          Total count of values from which the total price data line was generated.
 * @param distancesTraveledCount    Total count of values from which the distance traveled data line was generated.
 */
data class AnalysisDataLines(
    val volumes: List<AnalysisDataPoint>,
    val totalPrices: List<AnalysisDataPoint>,
    val distancesTraveled: List<AnalysisDataPoint>,
    val pricePerLiter: List<AnalysisDataPoint>,
    val volumesCount: Int,
    val totalPricesCount: Int,
    val distancesTraveledCount: Int
)
